slap-saver/public/stylesheets/author/articles.css
slap-saver/public/stylesheets/author/index.css
slap-saver/views/author/articles.ejs
slap-saver/views/author/index.ejs

feat: 내 기사 목록 css 조금 수정

---

slap-saver/controllers/articleController.js
slap-saver/controllers/authorController.js
slap-saver/controllers/userController.js
slap-saver/migrations/20210511094505-create-articles.js
slap-saver/models/article.js
slap-saver/public/javascripts/addSection.js
slap-saver/seeders/20210518020946-articles.js
slap-saver/views/articles/article.ejs
slap-saver/views/author/articles.ejs
slap-saver/views/author/checkArticle.ejs
slap-saver/views/author/desking/chiefEditor.ejs
slap-saver/views/author/desking/desk.ejs
slap-saver/views/author/desking/index.ejs
slap-saver/views/author/editArticle.ejs
slap-saver/views/author/newArticle.ejs

article  의 paragraphs 를 json 타입으로 수정
1.  기존에  text 타입이었던 paragraphs 를 json 으로 수정함
2. 동시에 기존에 사용하던 코드를 다 제거하고 사용하던 paragraphs 를 제거하고 새로운  paragraphs 를 적용했습니다.
3. 기존에 input 태그와 textarea 를 구분하지 않고 사용하던 문제가 있었기에 해당 문제도 수정했습니다.
4. 단락 제목은 더블클릭하면 수정할 수 있게 되었습니다.
- 아직 삭제 기능은 넣지 않았습니다.
특이 사항은 없습니다.

Paragraph refactor

---

slap-saver/db/docker-compose.yml
slap-saver/models/article.js

paragraphs 로 인한 에러 해결
1. 도커의 버전을 10.4 로 고정했습니다.
2. paragraphs 의 getter 를 만들었습니다.

Fix paragraphs

---

slap-saver/controllers/articleController.js
slap-saver/controllers/authorController.js
slap-saver/routes/author.js
slap-saver/views/author/desking/chiefEditor.ejs
slap-saver/views/author/desking/desk.ejs
slap-saver/views/author/desking/index.ejs
slap-saver/views/author/editArticle.ejs

fix: 여러 버그 수정

---

slap-saver/package-lock.json
slap-saver/package.json

packaage.json을 수정했습니다.
1. 사용하지 않는 명령 스크립트 제거
2. npx 스크립트제거
3. pm2 모듈은 글로벌로 설치하므로 dependencies에서 제거
4. 설치된 모듈을 사용하는 명령 스크립트들은 절대 경로를 사용하도록 수정
nodemon은 윈도우에서 pm2 사용이 원활하지 않아서 남겨두었습니다.

refactor: #104 package.json 명령어 수정

---

.github/ISSUE_TEMPLATE/refactoring-report.md

refactor: comment for refactor issue template

---

slap-saver/controllers/authorController.js
slap-saver/lib/constants/position.js
slap-saver/public/javascripts/author/today.js
slap-saver/routes/author.js
slap-saver/views/author/mypage/mypage.ejs
slap-saver/views/author/today/today.ejs
slap-saver/views/layout/adminLayout.ejs
slap-saver/views/partials/navbar.ejs
slap-saver/views/user/components/nav.ejs

- 기획서상 필요한 페이지 추가
- pdf 기획서를 바탕으로 author들의 마이페이지 추가 (`/author/mypage`)
- 오늘의 한마디 작성페이지 추가 (`/author/today`)
**사내메모함, 편집회의**기능이 금일 회의 후 없에는 것으로 협의됨

#138 add mypage

---

slap-saver/controllers/authorController.js
slap-saver/public/javascripts/navbar.js
slap-saver/views/author/login.ejs
slap-saver/views/partials/navbar.ejs

#134 #126 외부필진, 인턴 기능 추가
로그인 후 nav가 포지션에 맞게 뜨도록 수정
외부필진 오늘의 한마디 기능 추가 (미완)

#134 #126 authro/index 페이지 postion별로 다르도록 nav 수정

---

slap-saver/controllers/authorController.js
slap-saver/seeders/20210518020946-articles.js

seeder수정, preview페이지 오류 에러수정

---

saver-web/controllers/author/today/todayController.js
saver-web/models/todayword.js
saver-web/models/words.js
saver-web/public/javascripts/author/mytoday.js

내 오늘의 한마디 목록 - 오늘의 한마디 선택 여부 컬럼 추가

내가 작성한  오늘의 한마디 목록 추가

---

saver-web/controllers/author/today/todayController.js
saver-web/public/javascripts/author/editToday.js
saver-web/public/javascripts/author/today.js
saver-web/routes/author.js
saver-web/seeders/20210518094141-today-wordsjs
saver-web/views/author/today/editToday.ejs

오늘의 한마디 수정 페이지 생성 및 불러오기 기능 추가

오늘의 한마디 수정 페이지 생성 및 불러오기 기능 추가

---

saver-web/app.js
saver-web/controllers/author/today/todayController.js
saver-web/controllers/today/todayController.js
saver-web/controllers/user/userController.js
saver-web/public/javascripts/user/index.js
saver-web/routes/today.js
saver-web/seeders/20210518044141-word.js
saver-web/seeders/20210518054141-today-words.js
saver-web/views/user/index.ejs

메인페이지에서 오늘의 한마디 불러오는 코드 추가
#182

오늘의 한마디 메인페이지조회  - #182

---

saver-android/app/src/main/res/values-night/themes.xml
saver-android/app/src/main/res/values/colors.xml
saver-android/app/src/main/res/values/themes.xml

- 안드로이드 상단바 제거
- 상태바 투명화
- res/valuse/color.xml 에 transparent 컬러 추가
- res/valuse/themes 에 paren를 NoActionBar로 변경
- res/valuse/themes 에 statusBarColor를 위에서 추가한 transparent  변경하고, 아이콘의 색을 어둡게 바꾸기 위해  windowLightStatusBar를 true로 변경

feature/remove_actionbar 안드로이드 상단바 투명화

---

saver-android/app/src/main/java/com/seoul42/saver_android/MainActivity.kt
saver-android/app/src/main/java/com/seoul42/saver_android/MyFirebaseMessagingService.kt

- 안드로이드 notification 설정
- 알림 띄우기
- 클릭시 파이어베이스를 통해 보낸 링크로 이동
- [알림](https://developer.android.com/training/notify-user/build-notification)
- [링크 이동](https://androman.tistory.com/106)

feat : #230 안드로이드 notification 설정

---

saver-web/app.js
saver-web/lib/scheduleUpdate.js
saver-web/package-lock.json
saver-web/package.json

#242 특정 타임 자동 이벤트 함수 추가
- node-schedule 모듈을 이용해 특정 타임에 특정이벤트를 실행시키는 함수추가
[node-schedule ](https://coding8.tistory.com/34)

[feat]#242 특정 타임 자동 이벤트 함수 추가

---

saver-web/public/javascripts/infiniteScroll.js
saver-web/public/javascripts/totalShare.js
saver-web/public/javascripts/user/article.js
saver-web/views/user/article.ejs
saver-web/views/user/index.ejs

- [/] 과 [/articles/detail/{id}] 위치에 있는 공유버튼에 카카오톡
공유하기 기능을 추가
- 공유버튼에 카카오톡으로 공유하기 기능을 추가
- [public/javascripts/user/article.js] , [public/javascripts/infiniteScroll.js] 두 파일에 카카오톡 자바스크립트 키를 넣어서 실행시켜야 합니다.

feat: #253 공유버튼에 카카오톡 공유하기 기능 추가

---

saver-android/app/src/main/java/com/seoul42/saver_android/MainActivity.kt

-새 페이지가 로드되면 onCreate가 다시 호출되는 현상 수정
- webViewClient = WebViewClient() 가 작업중에 누락되어서 발생한 버그로 다시 추가해서 해결했습니다.
-

fix: 새 페이지 로드시 onCreate가 다시되는 현상 수정

---

saver-android/app/src/main/AndroidManifest.xml

-폰 회전시 앱이 다시 실행되는 버그 수정
-Manifest파일에 configChanges 속성 추가

fix: 안드로이드 폰 회전시 앱이 다시 실행되는 버그 수정

---

saver-web/package-lock.json
saver-web/public/javascripts/infiniteScroll.js
saver-web/public/javascripts/sharetotal.js
saver-web/public/stylesheets/user/components/articleCard.css
saver-web/views/layout/userLayout.ejs
saver-web/views/user/article.ejs

쉐어 모달 버튼
1. 쉐어 기능을 위한 모달 창 만들기.
2. 모달 창 안에 카카오톡 아이콘으로 쉐어 기능 연결
1. /public/stylesheets/user/components/articleCard.css 파일에 css코드 추가.
2. public/javascripts/infiniteScroll.js 파일에서 div class="article__control 부분 수정.
3. public/javascript/ 경로에 sharetotal.js 파일을 만들고 자바스크립트 코드 추가

feat: #252 쉐어 모달 버튼

---

saver-android/app/src/main/java/com/seoul42/saver_android/MainActivity.kt

- 공유버튼 클릭시 카카오톡으로 연결되지 않고 에러페이지를 띄우는 현상 수정
-카카오 측의 설명을 따라 webViewClient, webChromeClient를 재설정
-localhost 환경에서는 나타나지 않는 오류였는데 실제 페이지와 연결하니 오류가 발생했습니다. 앞으로 교차테스트가 필요할 것 같습니다.

fix : 안드로이드 공유버튼 클릭시 에러페이지 나타나는 현상 수정

---

saver-web/public/javascripts/infiniteScroll.js

-메인 화면에서 공유시 dev로 연결되는 버그 해결
-location.href 로 연결하여 현재 위치에서 보내도록 변경

fix: #288 메인 화면에서 공유시 dev로 연결되는 버그 해결

---

saver-web/public/javascripts/infiniteScroll.js
saver-web/public/stylesheets/user/reset.css

hotfix: 볼드체 aline 관련 버그 수정사항 main에 적용

---

saver-web/controllers/today/todayController.js
saver-web/public/javascripts/user/index.js

- 오늘의 뉴스 클릭시 이동이 되지 않는 현상을 수정했습니다.
-href에 값을 넣는 부분이 누락되어있어서 todayArticle을 가져오는 부분에서 id를 추가하고, 엘리먼트에 업데이트 하는 부분에서 주소를 만들어 넣었습니다.
-[jquery로 href 수정하는 방법](https://ooz.co.kr/46)

fix: 오늘의 뉴스 클릭시 이동 안되는 버그 수정

---

saver-web/controllers/today/todayController.js
saver-web/public/javascripts/user/index.js
saver-web/public/stylesheets/user/reset.css

hotfix: 오늘의 뉴스 클릭시 해당 링크로 이동하도록 수정

---

saver-web/public/javascripts/user/index.js
saver-web/public/stylesheets/icons/fold-button-text.svg
saver-web/public/stylesheets/user/components/articleCard.css

- 접기 버튼을 추가했습니다.
-[더 자세히]클릭시 기존에 있던 more-button 밑에 있는 이미지를 fold로 바꾸었습니다.
-[접기]클릭시 기존 형태로 되돌립니다.
-svg파일은 zeplin에서 가져왔습니다.

feat : 접기 버튼 추가

---

saver-web/public/javascripts/infiniteScroll.js
saver-web/public/javascripts/sharetotal.js
saver-web/views/user/article.ejs

- url 버튼 클릭하면 복사
- textarea를 생성했다 삭제하는 방식으로 구성.
모바일 환경에서 select()가 잘 안되는 이슈가 있다고 하는데 제가 android-chrome과 ios-safari에서 테스트 했을 때는 정상작동 했습니다.

feat: #298 url 공유하기 버튼 클릭 시 클립보드로 복사

---

saver-web/controllers/bookmark/bookmarkController.js
saver-web/models/bookmark.js
saver-web/models/subscriber.js

- 연관관계 설정 버그 수정
- 데이터베이스를 Bookmark로 불러와서 undefined로 나타나는 버그 수정
- 패스포트 설정이 되어있지 않아서 헤더에서 토큰 가져와서 유저 정보
가져오도록 수정
[외래키 이름선택](https://stackoverflow.com/questions/28056211/how-to-choose-name-of-foreign-key-column-using-sequelize-and-mysql)

hotfix: #309 북마크 모델 연관관계 설정 버그 수정

---

saver-web/app.js
saver-web/controllers/bookmark/bookmarkController.js
saver-web/middlewares/auth.js
saver-web/public/javascripts/bookmark.js
saver-web/public/javascripts/infiniteScroll.js
saver-web/public/javascripts/user/article.js
saver-web/routes/bookmark.js
saver-web/routes/subscriber.js
saver-web/views/layout/userLayout.ejs

-북마크 버튼 클릭시 북마크 데이터베이스에 정보가 등록되도록 추가
- axios로 /subscriber/bookmark/:{id}에 jwt토큰 전달->createBookmarkRequest를 통해 데이터베이스에 정보 저장
- 시퀄라이저에 find 함수는 존재하지 않음 -> findAll로 바꿈
[시퀄라이저 함수](https://sequelize.org/master/class/lib/model.js~Model.html#static-method-findByPk)

feat : #311 북마크 버튼 기능 추가

---

saver-web/app.js
saver-web/controllers/user/bookmarkController.js
saver-web/public/javascripts/bookmark.js
saver-web/public/stylesheets/icons/bookmark-black-transparent.svg
saver-web/public/stylesheets/icons/bookmark-black.svg
saver-web/public/stylesheets/user/common.css
saver-web/public/stylesheets/user/pages/bookmark.css
saver-web/routes/bookmark.js
saver-web/views/user/bookmark.ejs
saver-web/views/user/components/foo.ejs

북마크 페이지를 완성하기위한 베이스css 생성
css 사용방법은
saver-web/views/user/bookmark.ejs
밑부분에 주석으로 달아놨습니다

[feat] #304 북마크페이지 기본템플릿

---

saver-web/controllers/bookmark/bookmarkController.js
saver-web/public/javascripts/bookmark.js
saver-web/public/javascripts/bookmarkInfiniteScroll.js
saver-web/views/user/bookmark.ejs

-북마크 밀어서 삭제 구현
- [디자인 참고](https://codepen.io/ihorvorotnov/pen/OMYbvm)
- drag로 하면 모바일상에서 안먹혀서 touch로 구현했습니다. 테스트할때 개발자도구 열어서 모바일 모드로 바꾼뒤에 테스트해주세요.
- 모바일 모드 켜는 방법 : f12로 개발자 도구 켜기

feat : #327 북마크 밀어서 삭제

---

saver-android/app/src/main/AndroidManifest.xml
saver-android/app/src/main/res/values/strings.xml

refactor: 안드로이드 필요없는 부분 삭제

---

saver-web/public/stylesheets/user/pages/section.css
saver-web/views/user/loginedSection.ejs

- 팔로우 기본 섹션 추가
- default 섹션 추가
- 현재 팔로우 중인 카테고리를 카운트해서 처리
- css/default 관련 추가
- css관련 텍스트를 margin으로 처리

feat: #342 팔로우 중인 카테고리가 없을때 문구 추가

---

saver-web/app.js
saver-web/controllers/firebase/firebaseController.js
saver-web/public/javascripts/author/sendPush.js
saver-web/public/stylesheets/author/index.css
saver-web/routes/author.js
saver-web/routes/firebase.js
saver-web/views/author/pushPage.ejs
saver-web/views/author/pushSendPage.ejs
saver-web/views/layout/adminLayout.ejs
saver-web/views/partials/navbar.ejs

- 알림 보내기 페이지 다시 작성
- 이전에 작성한 브랜치의 상위 브랜치가 달라서 오류가 생겼던 것 같아 브랜치를 새로 생성했습니다.

feat: 기자측 알림 보내기 페이지 다시 작성

---

saver-web/app.js
saver-web/controllers/firebase/firebaseController.js
saver-web/public/javascripts/author/sendPush.js
saver-web/public/stylesheets/author/index.css
saver-web/routes/author.js
saver-web/routes/firebase.js
saver-web/views/author/pushPage.ejs
saver-web/views/author/pushSendPage.ejs
saver-web/views/partials/navbar.ejs

-author/push 페이지 제작
-firebase-adminsdk.json 가 없을 때 페이지가 터지는 이슈 해결
-페이지가 터지는게 다른 문제인 줄 알았는데 firebase-adminsdk.json가 없어서 생기는 문제였습니다. 
-nginx 로그쪽에 접근이 안되는 것 같아서 일단 클라이언트쪽에서 문제 상황을 알 수 있도록 로그 에러를 표시했습니다.

feat : author/push 페이지 제작

---

saver-web/config/config.js
saver-web/controllers/alarm/alarmController.js
saver-web/public/javascripts/author/index.js
saver-web/public/javascripts/author/sendPush.js
saver-web/views/author/desking/chiefEditor.ejs
saver-web/views/author/pushSendPage.ejs
saver-web/views/partials/footer.ejs

1. 푸시 알림과 알림 디비 생성 코드 합치기.
2. 타임존 설정 -> 새로운 디비를 생성 할 때 정확한 시간이 들어올 수 있도록 설정
알림 디비 생성 함수 리팩토링.
config.js 타임존 설정.

feat: #351 푸시 알림 통합

---

saver-web/public/javascripts/sectionFollowButton.js
saver-web/views/user/loginedSection.ejs

console log를 삭제하였고, follow 버튼을 클릭했을 때의 location.href를
수정했습니다.

fix : console log삭제와 location.href 수정

---

saver-web/public/javascripts/bookmark.js
saver-web/views/subscriber/login.ejs
saver-web/views/user/article.ejs
saver-web/views/user/components/foo.ejs
saver-web/views/user/section.ejs

- 로그인 여부에 따른 북마크버튼 동작 구현
- 비로그인 상태에서 로그인 완료하면 원래 이동하려던 페이지로 이동
- jwtToken으로 로그인 상태 판별.
- 로그인이 필요하면 /subscriber/login에 get요청으로 원래 이동하려던 페이지를 넘깁니다.
- 로그인 성공 시 받은 파라미터가 있다면 그 곳으로 이동하고 없다면 메인페이지로 이동합니다.

feat: #340 북마크 버튼 클릭 시 로그인 확인 

---

saver-web/public/javascripts/infiniteScroll.js

삽입된 영상이 화면을 넘어가지 않는선에서 16:9로 비율고정
iframe부분의 width, heigth를 비율형태로 변경

[fix]#206 영상 사이즈 16:9 비율 고정

---

saver-web/public/javascripts/infiniteScroll.js

[fix] max-width설정

---

saver-web/controllers/subscriber/subscriberController.js
saver-web/public/javascripts/sectionFollowButton.js
saver-web/views/subscriber/login.ejs

- 팔로우/로그인시 안드로이드 구독하기
- 팔로잉시 구독 취소하기
- 웹 코드에서 userAgent 체크 후 안드로이드인 경우 Android.subscribeTopic(value) 하도록 함

feat: #364 팔로우/로그인시 안드로이드 구독하기

---

saver-android/app/src/main/java/com/seoul42/saver_android/MainActivity.kt

fix: 안드로이드 userAgent 설정 추가

---

saver-web/controllers/author/article/articleController.js
saver-web/controllers/author/authorController.js
saver-web/controllers/author/today/todayController.js
saver-web/views/author/articles.ejs
saver-web/views/author/desking/chiefEditor.ejs
saver-web/views/author/desking/desk.ejs
saver-web/views/author/desking/index.ejs
saver-web/views/author/today/todaywordDesking.ejs
saver-web/views/author/todayArticle/todayArticleDesking.ejs

- 관리자 페이지 전체 페이지네이션으로 변경
- 페이지네이션 관련해서는 노션에 적어두었습니다.

feat: #375 관리자 페이지 전체 페이지네이션

---

saver-web/controllers/user/sectionController.js
saver-web/public/javascripts/sectionFollowButton.js
saver-web/routes/section.js

- 유저의 팔로잉 리스트를 체크하지 않아서 처음에 섞어서 나오는 현상 해결

fix: 팔로잉 리스트가 섞여서 나오는 버그 수정

---

saver-web/public/javascripts/bookmarkInfiniteScroll.js

fix : #383 북마크 css 수정

---

.gitignore
saver-ios/saver-ios.xcodeproj/project.pbxproj
saver-ios/saver-ios/AppDelegate.swift
saver-ios/saver-ios/Info.plist
saver-ios/saver-ios/ViewController.swift

- kakao app key config파일로 따로 관리
- .gitignore 추가
- config 파일 추가 및 설정

feat: #387 ios-secret-config

---

saver-android/app/src/main/java/com/seoul42/saver_android/MyWebClient.kt

fix : 안드로이드 카카오톡 쉐어 버그

---

saver-web/controllers/alarm/alarmController.js
saver-web/public/javascripts/alarmInfiniteScroll.js
saver-web/public/javascripts/bookmark.js
saver-web/public/javascripts/bookmarkInfiniteScroll.js
saver-web/public/javascripts/infiniteScroll.js
saver-web/public/javascripts/sectionFollowButton.js

- 로그인 실패 시의 처리가 없는 경우가 있어서 추가.

feat: #397 인증 미들웨어 error시 alert

---

saver-web/public/javascripts/sharetotal.js

feat:#307 ios-facebook share

---

saver-ios/saver-ios/AppDelegate.swift

push noti 를 클릭할 시 해당 첨부 url로 이동 기능 추가

feat: #403 deep link 적용 완료

---

saver-web/public/javascripts/sectionFollowButton.js
saver-web/views/subscriber/login.ejs

모바일 웹과 앱의 webkit이 구분되지 않아, 모바일 웹에서 webkit handler를
사용하는 이슈 해결

fix: #406 모바일 웹과 앱이 구별되지 않는 이슈 수정

---

saver-web/public/javascripts/sectionFollowButton.js
saver-web/public/javascripts/user/index.js
saver-web/views/subscriber/login.ejs

- 메인 화면 진입시/로그인시 구독/구독해제를 진행하도록 수정

fix: #430 안드로이드 구독 수정

---

saver-web/public/stylesheets/user/components/articleCard.css

- 유저 화면에서 ul ol 스타일 미적용되던 문제
- paragraph의 list 태그 스타일들을 수정

fix: ul/ol 스타일 편집

---

saver-web/app.js
saver-web/controllers/user/settingController.js
saver-web/public/javascripts/buildSetting.js
saver-web/public/javascripts/isAlive.js
saver-web/public/javascripts/setting.js
saver-web/public/stylesheets/user/pages/bookmark_alarm.css
saver-web/routes/setting.js
saver-web/views/user/components/nav.ejs
saver-web/views/user/setting.ejs

기획서 내부에 있던 설정창 프로토타입 제작
로그아웃, 알람끄기 기능 추가
로그인이 안되어있을시 바로 로그인창으로진입,
로그인이 되어있을경우 설정창진입,
로그아웃기능 추가,
알람끄기 토글보튼 추가, db와 연동(Subscriber의 alarmStatus section)

[feat] #435 설정페이지 프로토타입 제작, 로그아웃, 알람끄기

---

saver-web/controllers/author/today/todayController.js
saver-web/views/author/today/todaywordDesking.ejs
saver-web/views/author/todayArticle/todayArticleDesking.ejs

- updatedAt 기준으로 정렬
- 관리페이지에 표시되던 일시도 createdAt > updatedAt으로 변경

feat: #429 오늘의 기사, 오늘의 한마디 관리페이지 정렬

---

saver-web/views/layout/userLayout.ejs
saver-web/views/user/setting.ejs

fix #435 jquery 로드순서 변경

---

saver-web/controllers/author/today/todayController.js

fix: #441 오늘의기사 관리페이지에서 ampm제외

---

saver-web/views/user/article.ejs

fix: 디테일 페이지 카카오 공유 버그 해결

---

saver-web/controllers/user/sectionController.js
saver-web/public/stylesheets/user/pages/section.css
saver-web/views/user/section.ejs

- 로그인 안된 상태의 페이지에 변경된 텍스트 적용
- css 수정

fix: 로그인 안된 상태의 페이지 수정

---

saver-web/public/stylesheets/user/pages/section.css
saver-web/views/user/loginedSection.ejs
saver-web/views/user/section.ejs

- 화이트 박스 크기 조정
- footer에 가려지는 문제 수정

fix: 화이트 박스 크기 조정 & footer에 가려지는 문제 수정

---

saver-web/public/stylesheets/author/common.css
saver-web/public/stylesheets/author/index.css
saver-web/views/author/desking/chiefEditor.ejs
saver-web/views/author/desking/desk.ejs
saver-web/views/author/today/todaywordDesking.ejs
saver-web/views/author/todayArticle/todayArticleDesking.ejs

- 업데이트 버튼 위로 이동
- 업데이트 버튼 위로 이동
- 버튼 css 변경

fix: #450 업데이트 버튼 위치 이동

---

saver-web/public/stylesheets/author/common.css
saver-web/views/author/desking/chiefEditor.ejs

-인덱스에 따라 수정버튼위치가 달라져서 수정했습니다.
- 수정버튼 위치 조절

fix: chief 페이지 수정버튼 위치 조절

---

saver-web/controllers/user/userController.js
saver-web/public/javascripts/searchInfiniteScroll.js
saver-web/routes/index.js
saver-web/views/user/components/nav.ejs
saver-web/views/user/searchArticles.ejs

검색 기사 리스트 시퀄라이져 수정
광범위한 검색 엔진으로 동작할 수 있도록 코드 수정
검색 결과 스크롤 기존 인피니티 스크롤과 충돌 방지 작업
디자인 요청사항 추가 (Search 글자 없애기)
searchInfiniteScroll 관련 js 파일 ejs 파일 추가 등등

feat:#434 #238 홈화면 기사 검색

---

saver-web/public/stylesheets/author/index.css
saver-web/views/author/articles.ejs
saver-web/views/author/desking/chiefEditor.ejs
saver-web/views/author/desking/desk.ejs
saver-web/views/author/desking/index.ejs
saver-web/views/author/pushPage.ejs
saver-web/views/author/today/todaywordDesking.ejs
saver-web/views/author/todayArticle/todayArticleDesking.ejs

fix: 버튼 디자인 수정

---

saver-web/public/stylesheets/author/common.css
saver-web/views/author/articles.ejs
saver-web/views/author/desking/chiefEditor.ejs
saver-web/views/author/desking/desk.ejs
saver-web/views/author/desking/index.ejs
saver-web/views/author/mypage/mypage.ejs
saver-web/views/author/pushPage.ejs
saver-web/views/author/today/todaywordDesking.ejs
saver-web/views/author/todayArticle/todayArticleDesking.ejs
saver-web/views/partials/pageButton.ejs

- 페이지 이동 버튼 수정
- 테이블 형태 통일
- 페이지네이션 부분 partials 로 분리

fix:  페이지 버튼 수정

---

saver-web/views/user/components/foo.ejs

fix: #464 섹션메뉴 선택시 버튼 색상 미변경 버그 수정

---

saver-web/controllers/subscriber/subscriberController.js

fix: login 시 alarmstatus를 찾지 못하는 부분 수정

---

saver-web/controllers/author/today/todayController.js
saver-web/controllers/firebase/firebaseController.js

- 일부 데이터베이스 count 에서 조건 누락
- 해당부분 수정

fix: 전체 페이지 수 오류

---

saver-web/controllers/user/userController.js
saver-web/views/user/components/nav.ejs

1. nav.ejs 불필요한 코드 정리.
2. usercontroller.js 기사 내용으로도 시퀄라이져를 통해 디비와 비교할 수 있도록 코드 수정
**기사 제목으로만 검색에서,
제목 + 기사 내용으로 검색 범위 확장**

feat:#475 기사 검색 기능 추가

---

saver-web/public/javascripts/author/searchBox.js

- 이전 기사 prefix를 '이전 관련 기사 : '로 변경
- 이전기사 링크 추가시 맨 밑에 추가되도록 변경

fix: 이전 기사 prefix 변경

---

saver-web/controllers/author/article/articleController.js

-띄어쓰기로 분리해서 모든 단어를 포함할 경우 보여주도록 업그레이드

feat: 관리자 기사 검색 업그레이드

---

saver-web/public/javascripts/alarmInfiniteScroll.js
saver-web/public/javascripts/bookmarkInfiniteScroll.js
saver-web/public/javascripts/infiniteScroll.js
saver-web/public/stylesheets/user/common.css

- 알림페이지, 북마크 페이지에 ampm 아이콘이 나타나도록 수정
- 공유와 북마크 버튼이 오른쪽에 있도록 수정

fix:  #483 ampm 아이콘 미적용문제, 버튼 위치 문제 수정

---

saver-web/controllers/user/userController.js
saver-web/public/javascripts/searchInfiniteScroll.js
saver-web/public/stylesheets/user/pages/index.css
saver-web/views/user/searchArticles.ejs

1. 검색 결과가 없을 시 검색 내용이 존재하지 않는다는 문구가 적힌UI 추가
2. makeNoSearch() 함수 추가.
3. css, ejs 변경.

feat:#485 검색 결과 없음 페이지 수정

---

saver-web/controllers/user/userController.js
saver-web/public/javascripts/infiniteScroll.js

feat:#491 my section 결과 없음

---

saver-web/controllers/subscriber/subscriberController.js
saver-web/middlewares/auth.js

1. auth.js, subdcriberController.js 파일에 있던 토큰값을,
.env 경로에 선언되어 있는 변수에서 찾을 수 있도록 변경

feat: #502 토큰값 .env 로 옮기기

---

saver-web/public/javascripts/alarmStatus.js

- 토큰이 유효하지 않을 경우 로그인 페이지로 리다이렉트
- 메인 페이지에서 토큰이 유효하지 않을 경우 토큰 삭제 후 메인 페이지로 리다이렉트
-

feat: 토큰이 유효하지 않을 경우 로그인페이지로 리다이렉트

---

saver-web/controllers/author/article/articleController.js
saver-web/controllers/author/authorController.js
saver-web/controllers/author/today/todayController.js
saver-web/views/author/articles.ejs
saver-web/views/author/today/todaywordDesking.ejs
saver-web/views/author/todayArticle/todayArticleDesking.ejs

- 기사 정렬 순서를 updateAt 에서 createAt 기준으로 변경

fix: author페이지 기사 정렬 순서 변경

---

saver-web/public/javascripts/alarmInfiniteScroll.js
saver-web/public/javascripts/bookmarkInfiniteScroll.js

알림을 리스트에서 삭제하거나,
북마크를 리스트에서 삭제 했을때,
없음 ui 재출력 방지

fix:#512 알림 없음, 북마크 없음 재출력 방지

---

saver-web/controllers/article/articleController.js
saver-web/controllers/user/userController.js
saver-web/public/javascripts/infiniteScroll.js
saver-web/public/javascripts/searchInfiniteScroll.js
saver-web/views/user/article.ejs

기사 상단에 기자 이메일 추가
위의 두가지 작업중 1번작업으로 진행
메인페이지, 디테일페이지 적용

[feat]#528 기자이메일 추가

---

saver-web/controllers/today/ampmController.js

- am/pm기사에서 email이 undefined
- db불러올 떄 email을 포함시켜서 해결.

fix: #533 ampm기사 이메일 undefined

---

saver-web/public/javascripts/bookmarkInfiniteScroll.js

웹상에서는 문제가 보이지 않는 반면 모바일 웹과 어플리케이션에서 북마크 관련 이미지가 재출력 되는 오류를 발견해 수정합니다.
bookmarkinfiniteScroll.js 수정

fix: 북마크 없음 재출력 방지

---

saver-web/public/javascripts/author/searchBox.js
saver-web/views/partials/navbar.ejs

- 기사 링크 시인성 개선
- 링크 문구 변경
- author 페이지 상단 Navi-bar 버튼 깨짐
- 기사 링크 시인성 개선
하늘색 -> 파란색
- 링크 문구 변경 
이전 관련 기사 -> Saver 관련 기사)
- author 페이지 상단 Navi-bar 버튼 깨짐
기자 프로필 이미지 없을 때 디폴트 이미지 보여지도록 수정

링크 색상 변경 및 링크 기사 문구 변경

---

saver-android/app/build.gradle
saver-android/app/src/main/res/drawable/ic_arrow_back_black.xml
saver-android/app/src/main/res/layout/activity_main.xml
saver-web/controllers/today/ampmController.js
saver-web/public/stylesheets/user/components/topbar.css

android app 
web
- android app 외부 링크 WebView 타이틀바 배경 수정
- 아이폰에서 상단 검색아이콘 파란 배경 보이는 문제
- AM7 & PM7 기사 링크 색상 하늘색에서 검은색으로 변경, 언더바 없애기

topbar search icon background color change

---

saver-web/public/javascripts/infiniteScroll.js
saver-web/public/stylesheets/user/components/footer.css
saver-web/views/user/components/foo.ejs

모바일에서 이용약관 레이아웃 깨지는 문제 수정
메인화면 하단 모바일 이용 약관 레이아웃 수정

모바일 이용약관 레이아웃 조정
